alter table DEPOSIT_DEPOSITMEDTERM add constraint FK_DEPOSIT_DEPOSITMEDTERM_ON_QR_CODE foreign key (QR_CODE_ID) references SYS_FILE(ID);
create index IDX_DEPOSIT_DEPOSITMEDTERM_ON_QR_CODE on DEPOSIT_DEPOSITMEDTERM (QR_CODE_ID);
